version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/go/src/app
    command: ["air"]
    networks:
      - shared_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    networks:
      - shared_network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "3001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    depends_on:
      - db
    networks:
      - shared_network

volumes:
  db-data:
    driver: local

networks:
  shared_network:
    driver: bridge